# GitHub Action for generating a contribution graph with a snake eating your contributions.
name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:        # manual trigger from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v2

      # Generates the snake
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: hafizecim
          color_snake: "#FF69B4"          # yılan rengi (pembe)
          color_dots: "#FDDDE6,#FFC0CB,#FF69B4,#DB7093,#C71585" # katkı noktaları
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Check git status
      - run: git status

      # Commit & push changes
      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist
          git commit -m "Update contribution snake" || echo "No changes to commit"
          git push origin master

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
